
FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y iputils-ping curl\
    build-essential \
    python3-dev \
    gcc \
    libffi-dev \
    libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install mlflow

ENV MLFLOW_ARTIFACT_ROOT=/app/mlruns

EXPOSE 5001

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001"]