FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y iputils-ping curl\
    build-essential \
    python3-dev \
    gcc \
    libffi-dev \
    libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY setup.py .

RUN pip install --no-cache-dir -r requirements.txt

COPY api_directory/ api_directory/
#COPY cache/ cache/

EXPOSE 8000

CMD ["uvicorn", "api_directory.api:app", "--host", "0.0.0.0", "--port", "8000"]
